### ISSUE TITLE
Status: Processing in progress

### ISSUE THREAD

**Issue by felorodri** [wfpaisa/ps_payu#1]
Hola!

Estoy intentando usar este módulo en la versión 1.7.4.2 de prestashop.Estoy realizando el proceso de compra de un producto pagando mediante PayU y pese a que la transacción es aprobada en "Test mode" el estado de la orden se queda siempre en "Processing in progress" a menos de que cambie el estado manualmente desde el dashboard. Este comportamiento es normal? Debido a esto, también noté que la factura y el pdf con la información de envío del producto se generan automáticamente, es este también un comportamiento esperado? Si no es así, hay una versión en específica de prestashop en la que se deba usar este módulo?

De antemano, muchas gracias!

**Comment by wfpaisa** [comment]
Hola felodri,  la orden debe de cambiar automaticamente una vez que payu lo compruebe, debe de funcionar en cualquier versión de prestashop 1.7.x, de hecho tengo la 1.7.4.2 y me funciona perfecto, acabo de agregar al módulo unas notas que creo que es lo que te falta.
![secscreenshot](https://user-images.githubusercontent.com/1735752/44273892-51c26d00-a206-11e8-97fc-cc6c317d1e95.png)
Saludos

**Comment by felorodri** [comment]
Muchas gracias por responder y por actualizar la información del Readme.md @wfpaisa. Estaré haciendo nuevas pruebas esta semana y te indico que tal resulta todo. Nuevamente muchas gracias.

**Comment by felorodri** [comment]
Hola! Pude confirmar que efectivamente el método de pago funciona correctamente. Muchas gracias por las aclaraciones. Doy por cerrado el issue.
