### ISSUE TITLE
Problema al procesar la compra y elegir el método de pago dentro del modulo PayU Latam

### ISSUE THREAD

**Issue by jhonnyleeb** [wfpaisa/ps_payu#10]
Al procesar la compra y elegir el método de pago dentro del modulo PayU Latam, solo con dar clic a cualquier opción ejemplo: PSE, automaticamnete me envía factura de compra al cliente y me procesa un pedido, como si el cliente hubiera procesado la compra con éxito, con estado: "preparación en curso" y en los pedidos del cliente el mismo esta, te agradezxco la ayuda.

![Sin título](https://user-images.githubusercontent.com/7004148/78507051-7eacf600-7743-11ea-9562-7e1821d70f37.png)
![payu_1](https://user-images.githubusercontent.com/7004148/78507055-82407d00-7743-11ea-97ef-a12480a90390.jpg)

**Comment by wfpaisa** [comment]
Hola, puedes confrontar  que concuerde los estados de pedido con los estados de este archivo `https://github.com/wfpaisa/ps_payu/blob/master/controllers/front/confirmation.php#L31`
