### ISSUE TITLE
Problemas en Carga de Modulo

### ISSUE THREAD

**Issue by jerv66** [wfpaisa/ps_payu#11]
Buenas noches, tengo problemas con la carga del modulo, eh realizado la descarga de archivos y los eh cargado en una carpeta tal cual como lo indica pero siempre me sale un error "Este archivo no es un módulo en formato ZIP válido."

por favor me pueden ayudar... estoy instalando en prestashop 1.7

**Comment by wfpaisa** [comment]
Buenas noches, por el momento intenta subiéndolo por ftp o ssh a tu carpeta de módulos
