### ISSUE TITLE
Creación de orden con pago rechazado

### ISSUE THREAD

**Issue by daferlopez** [wfpaisa/ps_payu#12]
Hola, buena noche.

Estoy implementando el pago con el módulo PayU que desarrollaste, sin embargo el sistema me está generando confirmación de orden, aún cuando la transacción fue rechazada.

Si bien al rechazarse la transacción el sistema muestra mensaje de rechazo al volver al comercio, igualmente envía correo confirmando la orden.

Sabes si esto se debe a configuración o desarrollo del módulo.

Gracias!

**Comment by wfpaisa** [comment]
Buenos días Daniel, si es correcto el funcionamiento la orden se genera
siempre indiferente si el pago es confirmado o no, cada pedido tiene un
histórico donde se detalla su estado y también debería ser tarea del
administrador del e-commerce hacer frente y contactar al cliente para
intentar recuperar el pago, recuerda que si un cliente llega hasta el
pedido es por que hubo una intención de compra o un interés, de esta forma
se aumentan las conversiones.

**Comment by daferlopez** [comment]
Men, gracias por tu respuesta!
