### ISSUE TITLE
Error en aprobación de transacciones modo pruebas

### ISSUE THREAD

**Issue by daferlopez** [wfpaisa/ps_payu#13]
Hola de nuevo :$,

Estoy testeando el módulo pero al intentar realizar una transacción como aprobada, paso como nombre APPROVED, según lo indicas pero siempre las rechaza el sistema.

Me podrías indicar por favor que puedo revisar.

Gracias!

**Comment by carlitossuper1** [comment]
Me uno a este comentario. Probando el módulo, PayU dice que necesita hacer una comprobación adicional y no aprueba el pago de pruebas
