### ISSUE TITLE
Error con la información enviada por la tienda a PayU

### ISSUE THREAD

**Issue by YZaube** [wfpaisa/ps_payu#14]
Hola Wfpaisa,

Primero gracias por este modulo ha sido de gran ayuda. Por otro lado el día de hoy se realizó un pedido y al pasar a la pasarela de pagos cuando cargaba la pestaña de PayU arrojó error debido a que la información enviada por la tienda (nosotros) era erronea.

Sin embargo intente hacer otro pedido y si me dejó proceder con el pago. 

Usted sabe esto por qué se puede generar ya que por lo visto no es constante?

Muchas Gracias

**Comment by wfpaisa** [comment]
Hola, intentaste realizar la prueba con los mismos productos y el mismo usuario?

**Comment by YZaube** [comment]
Hola, acabo de intentar 2 productos que me presentaron el error que comento, pero ya deja proceder a diligenciar los datos en la pasarela de pagos.

Es raro, puede que sea por la velocidad de respuesta del servidor de la tienda al enviar la información a PayU?

Gracias
