### ISSUE TITLE
Error "No se puede crear solicitud de pago"

### ISSUE THREAD

**Issue by kvnn10** [wfpaisa/ps_payu#2]
Cuando intento comprar me saca este error: "No se puede crear solicitud de pago". Error interno del servidor. adjunto imagen 
![error payu](https://user-images.githubusercontent.com/29876188/47240190-37933f80-d3ad-11e8-816d-d9308baf623e.png)

**Comment by wfpaisa** [comment]
Hola Kevin Aviles, primero comprueba que estas ingresando las configuraciones bien en el administrador del modulo, si sigue igual, intenta hacer un envío del formulario solo, mira aca la documentación https://github.com/wfpaisa/payu-raw, solo debes cambiar en el archivo conf.php por tus datos.
