### ISSUE TITLE
ayuda con tu módulo payulatam 1.7 errores

### ISSUE THREAD

**Issue by orgonita2006** [wfpaisa/ps_payu#3]
hola, primero que todo gracias por el módulo, fué fácil de instalar y están claras las instrucciones pero me sale un error que no logro superar y es que me sale en el checkout después de elegir pagar con payulatam https://checkout.payulatam.com/ppp-web-gateway-payu/ allí sale que hay un problema con que no identifica mi ID de comerciante o que no identifica los parámetros dados, he puesto los datos al contrario o como he visto que dejan el ID de país en 0, pero de ninguna manera parece conectar con el sistema y nunca me muestra los medios de pago, he ensayado metiendo moneda local o pagando en euros y siempre sale el error, curiosamente siempre recibo los correos de confirmación de pago aún cuando nunca me ofreció formas de pago, qué podrá ser?.

Te agradecería tu colaboración, mi web es orgonita.org allí podrás hacer el checkout y ver qué sale, gracias 

Uno de los errores dice: 

Tenemos inconvenientes con los datos que estamos recibiendo para procesar tu pago.

Comunícate con la tienda para que puedas ingresar de nuevo y completar el pago.

Integración web checkout
No se pudo crear solicitud de pago	
![duendes](https://user-images.githubusercontent.com/44769170/47990691-73860e80-e0e8-11e8-8321-e92f24b70f8f.jpg)

Otro tipo de error que sale es:
 Comunícate con la tienda para que puedas ingresar de nuevo y completar el pago.

Integración web checkout
No se pudo crear solicitud de pago	
Parámetro
Descripción
Valor recibido
Mensaje de error

accountId

Identificador de la cuenta del usuario para cada país que tenga asociado el comercio, al enviarla se despliegan solo los medios de pago pertenecientes a dicho país.

Parámetro inválido

**Comment by wfpaisa** [comment]
Hola Katalina,
1. Intenta esto: en la configuración del módulo: habilita el modo test y deshabilita el sandbox. 
2. Si lo anterior no funciona: Debemos estar seguros de que los parámetros enviados sean correctos: intenta descargando este repositorio: https://github.com/wfpaisa/payu-raw/, (Producción test)

espero que tras esto identifiquemos que puede ser.

**Comment by santivasa** [comment]
Buenos Dias como estas ? muchas gracias por el modulo esta muy bueno y bien explicado , te queria comentar que tengo un problema al procesar el pago me sale el siguiente error

![image](https://user-images.githubusercontent.com/65300785/81836185-bf4d1b80-9508-11ea-8acf-c6d424d92dba.png)

Te agradecera tu colaboracion Gracias

**Comment by wfpaisa** [comment]
La firma tiene un error, puede que estés ingresando mal los datos solicitados.
https://github.com/wfpaisa/ps_payu/blob/master/img/screenshot.png
