### ISSUE TITLE
Ayuda envio de pago

### ISSUE THREAD

**Issue by joedriva** [wfpaisa/ps_payu#4]
HOla buen dia, estoy implementando este modulo de payu y el enviar el pago me sale este error

![image](https://user-images.githubusercontent.com/7028242/52020741-76628680-24c0-11e9-86b8-7fe69fe4903e.png)

no se si es por lo del multi lenguaje, espero tu ayuda

**Comment by wfpaisa** [comment]
Hola Joedrive, el error no me dice nada, debes de revisar el archivo (error.log) de tu servidor para identificar el problema.

**Comment by joedriva** [comment]
Hola el error que muestra en el log del servidor es el siguiente

![image](https://user-images.githubusercontent.com/7028242/52092413-842e0f80-2585-11e9-8a21-38b66d6340d6.png)

parace ser por la version de php, ya que no la puedo actualizar porque es un servidor compartido alguna idea de como lo puedo solucionar

**Comment by wfpaisa** [comment]
no me he topado con un problema similar, aunque te puedo recomendar crear tu servidor en Digitalocean, veras que el sitio te va a cargar mucho mas rápido y te olvidas de este tipo de problemas.

**Comment by joedriva** [comment]
Hola ya solucione, tuve que cambiar en classes/Mail.php en la linea 872 la funcion idn_to_ascii() que es propia de php y como el server utiliza una version anterior, genera error, se debe descargar la clase que encontré en este repositorio https://github.com/algo26-matthias/idna-convert y reemplazar la funcion por la de esta libreria, la funcion quedaria de la siguiente forma

    public static function toPunycode($to)
    {
    $IDN = new IdnaConvert();

        $address = explode('@', $to);
        if (empty($address[0]) || empty($address[1])) {
            return $to;
        }

        //return $address[0].'@'.$address[1];
        return $address[0].'@'.$IDN->encode($address[1]);
    }

incluir al inicio de la clase el include donde ubique la libreria descargada
