### ISSUE TITLE
Estados repetidos en módulo de Pedidos

### ISSUE THREAD

**Issue by jonathangallego** [wfpaisa/ps_payu#5]
Hola buen día Felipe, primero que todo gracias por el módulo, estoy presentando un error en el módulo de **Pedidos** después de haber instalado el módulo de **PayU**, cada vez que se hace un pedido nuevo, en el Tab de **Estado**, se está repitiendo el mismo estado muchas veces con una diferencia de segundos del mismo estado.

![image](https://user-images.githubusercontent.com/50707749/57863145-2681a400-77bf-11e9-98e9-223cd33d80bd.png)

¿Cual será el por qué de este inconveniente y una posible solución? ya que antes de la instalación del módulo se tenia un solo estado sin repetirse N cantidad de veces.

Actualmente estoy trabajando con esta versión de PrestaShop: **1.7.2.4**

**Comment by wfpaisa** [comment]
Hola Jonathan, esto sucede por que Payu valida multiples veces el estado de pedido, 
intenta revisando esta configuración: 
```
Ir a la configuración técnica de payu e ingresar los datos:
URL de respuesta: https://midominio.com/module/ps_payu/response
URL de confirmación: https://midominio.com/module/ps_payu/confirmation
```
si aun sigue igual, hay que programar en el controlador una validación de estado. (si es un problema con el modulo , te invito a solucionarlo, muchas personas te agradecerían ;) )

**Comment by wfpaisa** [comment]
a, no olvides si lo solucionas en escribir como lo hiciste. o hacer un push request. saludos.
