### ISSUE TITLE
Ayuda con modulo PayU latam - categoria

### ISSUE THREAD

**Issue by ariasjf00** [wfpaisa/ps_payu#6]
Instalé
[Configuracion PayU.pdf](https://github.com/wfpaisa/ps_payu/files/3298584/Configuracion.PayU.pdf)
 el modulo siguiendo las intrucciones y lo veo en modulos pero no en la categoria pago, puede ser que por esto no me aparece en metodos de pago?
AL ingresar a preferencias si apararece para su seleccion, pero al cargar carrito de compas no me aparece opcion de pagos.

**Comment by wfpaisa** [comment]
Buenas noches Arias, al instalarlo lo configuraste?

**Comment by ariasjf00** [comment]
Felipe, gracias por tu pronta respuesta, una vez instalado ingresé a mi cuenta de PayU y copie Mecardo, cuenta y clave. tal como aparece en la parte superior de la configuración del modulo adicionalmente active PayU en método de envio. Note algo configure pago en cheque y si desactivo PayU en el método de envío, aparece este método pero cunado activo PayU no aparece ninguno.
Este modulo de PayU lo estoy usando en otra tienda de prestashop que esta en 1.6 y funciona bien, pero en esta que esta en 1.7 no me aparece. Sera que tiene que ver con que la URL que tiene mi cuenta d ePayU esta apuntando a la otra tienda? sera que tengo que crear una cuenta en Payu específicamente para cada tienda? a tienda se llama shienmaster.com.co

voy a contactar a los de PayU para aclarar esto, pero si hay alguna forma de verificar porque no aparece, por ejemplo pornes un consolelog("variable"+xxxx) y verificar por inspección si esta haciendo el llamado.

**Comment by wfpaisa** [comment]
Mmm , no estoy seguro, debo de revisar, voy a buscar un tiempo este fin de semana para instalar un Prestashop y revisar si hay errores.

**Comment by wfpaisa** [comment]
Hola @ariasjf00 arias, debes revisar tu configuración, ya que otro usuario reporta con un error pero se ve que esta funcionando. 
https://github.com/wfpaisa/ps_payu/issues/7
