### ISSUE TITLE
Error en con /module/ps_payu/confirmation

### ISSUE THREAD

**Issue by guillermo259** [wfpaisa/ps_payu#7]
se realizo una compra en mi pagina y payu envió este correo correo electrónico.

![error para creador del plugin](https://user-images.githubusercontent.com/51971690/59950577-fbcce000-943b-11e9-93c4-2a8682d34060.jpg)

también a la hora de aceptar el pago se repite el estado una y otra vez con segundos de diferencias

![error para creador del plugin 2](https://user-images.githubusercontent.com/51971690/59950745-6e3dc000-943c-11e9-9752-155c1ff55230.jpg)

tengo la configuración del payu como comentas en el plugin 

Versión de PrestaShop: 1.7.2.4

**Comment by wfpaisa** [comment]
Hi @guillermo259 vale vamos por pasos, intenta navegando a la ruta que te indica el error (https://midominio.com/module/ps_payu/confirmation) y revisa si sale error o queda en blanco, lo otro sería que entres al archivo (https://github.com/wfpaisa/ps_payu/blob/master/controllers/front/confirmation.php) y te envíes la firma y como se genera:
```
$firma = "$ApiKey~$merchantId~$referenceCode~$newValue~$currency~$statePol";
$firmaMd5 = md5($firma);
$sign = $_REQUEST['sign'];
```
con el fin de comprobar si coinciden.

Verificas primero esto y luego miramos como realizar un condicional para ver si el pago fue aceptado no lo ingrese nuevos registros.

**Comment by maryleon184** [comment]
Hola,
Tengo el módulo configurado en mi Prestashop, cuando le doy a la opción de pagar por payu me abre la ventana de pago de payu, pero si cierro esa ventana y no realizo el pago, en Prestashop me genera el pedido como Preparación en curso. ¿Sabeís porque puede ser esto?
Muchas Gracias¡

**Comment by maryleon184** [comment]
Te adjunto la versión de Prestashop 1.7.4.2

**Comment by wfpaisa** [comment]
Hola maryleon, si no estoy mal esta bien el funcionamiento, todas los pedidos entran en Error o Pendiente, y si configuraste bien en PayU la variable de la url de retorno, este responderá después de un tiempo si es: (Expirada, Declinada, Aprobada).

**Comment by maryleon184** [comment]
Ok voy a revisar las url y te digo algo. Gracias por tu respuesta

**Comment by wfpaisa** [comment]
Con gusto, recuerda crear un nuevo issue si detectas un error.
