### ISSUE TITLE
PAYU instaldo pero se activa como medio de pago

### ISSUE THREAD

**Issue by ariasjf00** [wfpaisa/ps_payu#8]
He instalado el modulo y seguido las instrucciones de instalación, configure mi mercado id etc. adicionalmente fui a preferencias y active PayU en todo donde aplicaba.
Si entro a medios de pago en configuración  no aparece y si realizo un pedido desde la tienda no muestra los medios de pago queda como carrito de compra únicamente.
Adjunto pantallas
Prestashop 1.7.5.2
[gtechniq-payu-issue.pdf](https://github.com/wfpaisa/ps_payu/files/3521509/gtechniq-payu-issue.pdf)

**Comment by wfpaisa** [comment]
Fue solucionado reinstalado el prestashop.
