### ISSUE TITLE
Me marca las ordenes como "pendiente" después del pago.

### ISSUE THREAD

**Issue by marlon8511** [wfpaisa/ps_payu#9]
Hola, tengo configurada correctamente las url confirmation y response en PayU.
En el modulo tengo asignado correctamente los IDs de los estados

Cuando un cliente realiza un pedido el primer estado es pendiente, después de que efectúa el pago y PayU lo aprueba en vez de asignarle el estado "pago aceptado" le vuelve asignar "pendiente" y me toca cambiarlo manualmente.

Mi version de prestashop es 1.7.6.4

De antemano gracias por la ayuda

**Comment by wfpaisa** [comment]
Hola Marlon, tenemos los siguentes escenarios:
1. PayU esta retornando mal la respuesta. (puedes intentar de nuevo haber si el problema persiste, ver los siguientes pasos)
2. Los estados de pago han sido cambiados.(revisar si has cambiado los estados de pedido por defecto, intentar con una instalación desde cero)
3. Ha cambiado algo en el API de PayU (revisar la respuesta de PayU)

quedo atento a tus comentarios. saludos

**Comment by marlon8511** [comment]
Hola, nuevamente 

Tengo configurada correctamente las url confirmation y response en PayU.
En el modulo tengo asignado correctamente los IDs de los estados

Cuando la respuesta de PaYU es transaccion rechazada en el modulo en PS me la esta marcando como pendiente

De antemano gracias por la ayuda

**Comment by wfpaisa** [comment]
Hola Marlon, puedes verificar que los estados de pedido concuerden desde la configuración de estados de pedido de prestashop o modificando el modulo en(/controllers/front/confirmation.php):
![DeepinScreenshot_select-area_20200715102151](https://user-images.githubusercontent.com/1735752/87563780-3d52ad80-c685-11ea-83f4-ce31b92ad92d.png)
![DeepinScreenshot_select-area_20200715102252](https://user-images.githubusercontent.com/1735752/87563784-3e83da80-c685-11ea-909d-8d15559c2521.png)

**Comment by marlon8511** [comment]
Hola
Tengo lo siguiente en los estados de Prestashop

**2** Pago Aprobado
**15** Pendiente (PayU)
**16** Error (PayU)
**17** Rezchazado (PayU)

En el modulo de Payu Tengo:
PS_PAYU_PAYMENT_STATUS_APPROVED **2**
PS_PAYU_PAYMENT_STATUS_REJECTED **17**
 PS_PAYU_PAYMENT_STATUS_PENDING **15**

El archivo /controllers/front/confirmation.php esta asi:

switch ($statePol) {
					case 4:
						$estadoTxt = Configuration::get('PS_PAYU_PAYMENT_STATUS_APPROVED');
						break;
					case 6:
						$estadoTxt = Configuration::get('PS_PAYU_PAYMENT_STATUS_REJECTED');
						break;
					case 7:
						$estadoTxt = Configuration::get('PS_PAYU_PAYMENT_STATUS_PENDING');
						break;
					case 104:
						$estadoTxt = 8;
						break;
					default:
						$estadoTxt = Configuration::get('PS_PAYU_PAYMENT_STATUS_PENDING');

Y me siguen quedando las ordenes como pendientes.

Que podrá estar pasando. Cabe anotar que tengo la última version de Prestashop

Gracias

**Comment by wfpaisa** [comment]
lo siento, mira comprueba esto que los case correspondan:
![DeepinScreenshot_select-area_20200723064303](https://user-images.githubusercontent.com/1735752/88295022-811b6780-ccc2-11ea-972a-ba28f4679aee.png)

**Comment by marlon8511** [comment]
Hola no me llego la respuesta.

Gracias

**Comment by wfpaisa** [comment]
lo siento, mira comprueba esto que los case correspondan:
![DeepinScreenshot_select-area_20200723064303](https://user-images.githubusercontent.com/1735752/88295022-811b6780-ccc2-11ea-972a-ba28f4679aee.png)

**Comment by marlon8511** [comment]
Hola 

Una consulta esos estados que me dices que cambié en el archivo confirmation.php no son los que maneja payu como respuesta de la transacción. 

http://developers.payulatam.com/es/web_checkout/variables.html

Quiero asegurarme.

Gracias

**Comment by wfpaisa** [comment]
Marlon, tienes razón, puedes intentar enviarte al correo el `$statePol` de esta forma verificas que estado te esta respondiendo Payu y asi hacer las modificacines respectivas.
